CREATE DATABASE IF NOT EXISTS rh;

USE rh;


CREATE TABLE users(
  id INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(45) NOT NULL,
  statusProcesso VARCHAR(45) NOT NULL,
  iniciado_em VARCHAR(45) NOT NULL
);